void init(void);
void initGLFW(void);
void initGLEW(void);
void make_resources(void);
void shutDown(int return_code);
void mainLoop(void);
void resize(GLFWwindow* window, int width, int height);
void keyCallback(GLFWwindow* window, int key, int scancode, int action, int modifiers);
void mouseButtonCallback(GLFWwindow* window, int button, int action, int modifiers);
void draw();
